spec-version: 0.30.0
name: automonad
author: Asad Saeeduddin
maintainer: masaeedu@gmail.com
license: MIT

build-type: Simple

source-dirs: src
dependencies:
  - { name: "base", version: ">=4.12 && <4.13" }
  - first-class-instances

ghc-options: -Wall
default-extensions:
  - GADTs

  - StandaloneDeriving
  - DeriveFunctor
  - DerivingVia
  - GeneralizedNewtypeDeriving

  - ScopedTypeVariables
  - RankNTypes

  - TypeApplications
  - TypeOperators
  - MultiParamTypeClasses

  - ConstraintKinds
  - DataKinds
  - PolyKinds
  - KindSignatures

  - UndecidableInstances
  - UndecidableSuperClasses
  - FlexibleInstances
  - FlexibleContexts
  - DefaultSignatures

  - TemplateHaskell
  - TypeFamilies
  - NoQuantifiedConstraints
  - NamedFieldPuns
  - ViewPatterns
  - TupleSections

library: {}
executable:
  main: Main.hs
